#! /usr/bin/python3
import sys
import pathlib
import os
import time
import stat
import pwd

path = pathlib.Path(__file__).parent.absolute()
opt_l = False
opt_L = False

#sprawdzenie argumentów
if len(sys.argv) > 4:
    print("Za dużo argumentów.")
    exit()
elif len(sys.argv) > 1:
    for i in range(1, len(sys.argv)):
        if sys.argv[i] == "-l": opt_l = True
        elif sys.argv[i] == "-L": opt_L = True
        else: path = sys.argv[i]

if pathlib.Path(path).exists() == False\
or pathlib.Path(path).is_dir() == False:
    print("Nieodpowiednia ścieżka do katalogu.")
    exit()

#pobranie ścieżek wszystkich plików we wskazanym folderze
files = os.listdir(path)
files.sort(key=str.lower)

#wyświetlenie wymaganych informacji
for file in files:
    #nazwa pliku
    print(file.ljust(30), end="")
    stats = os.stat(path + "/" + file)
    if opt_l == False and opt_L == False : print()

    if opt_l:
        #rozmiar
        print("{}".format(stats[6]).ljust(10), end="")
        #czas modyfikacji
        mod = time.localtime(stats[8])
        print("{}{}{}{}{}{}{}{}{}{}{}".format(\
        mod[0],'-',mod[1],'-',mod[2],' ',mod[3],':',mod[4],':',mod[5]).ljust(20)\
        , end="")
        #uprawnienia
        perm = "-"
        if (stats[0] & stat.S_IFDIR) == 0:
            perm = "d"
        octperm = oct(stats[0])[-3:]
        for number in octperm:
            if number == '0': perm += "---"
            elif number == '1': perm += "--x"
            elif number == '2': perm += "-w-"
            elif number == '3': perm += "-wx"
            elif number == '4': perm += "r--"
            elif number == '5': perm += "r-x"
            elif number == '6': perm += "rw-"
            elif number == '7': perm += "rwx"
        print(perm.ljust(15), end="")
        if opt_L == False: print()

    if opt_L:
        #nazwa wlasciciela
        user = pwd.getpwuid(stats[4])
        print(user[0])
